classmenu/urls.py
from django.urls import path

from .views import (
    ClassMenuView,
    ClassSettingsView,
    AddAssignmentView,
    AddPollView,
)

from .get_or_post_views import (
    SendPublicMessagePostOnlyView,
    BlockJoinRequestPostOnlyView,
    ChangeClassDescriptionView,
    JoinResponseView,
    ClassDataByStepView,
    PollCastedView,
    ClosePollView,
    AllStudentsView,
    RemoveStudentView,
    LeaveClassView,
)

app_name = 'classmenu'

urlpatterns = [
    path('<classID>/', ClassMenuView.as_view(), name="class"),
    path('<classID>/send-message/', SendPublicMessagePostOnlyView.as_view()),
    path('<classID>/block-join-request/', BlockJoinRequestPostOnlyView.as_view()),
    path('<classID>/change-class-desc/', ChangeClassDescriptionView.as_view()),
    path('<classID>/join-response/<enrId64>/', JoinResponseView.as_view()),
    path('<classID>/settings/', ClassSettingsView.as_view(), name="settings"),
    path('<classID>/settings/leave/', LeaveClassView.as_view()),
    path('<classID>/settings/all-students/', AllStudentsView.as_view()),
    path('<classID>/settings/remove-student/', RemoveStudentView.as_view()),
    path('<classID>/assignments/add-assignment/', AddAssignmentView.as_view(), name="add-assignment"),
    path('<classID>/polls/add-poll/', AddPollView.as_view(), name="add-poll"),
    path('<classID>/get-class-data/<int:stepCount>/', ClassDataByStepView.as_view()),
    path('<classID>/poll-casted/', PollCastedView.as_view()),
    path('<classID>/close-poll/', ClosePollView.as_view()),
]

edusatchel/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from .views import DefaultView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', DefaultView.as_view()),
    path('admin/', admin.site.urls),
    path('register/', include('register.urls', namespace='register')),
    path('home/', include('home.urls', namespace='home')),
    path('class/', include('classmenu.urls', namespace='classmenu')),
    path('assignment/', include('assignment.urls', namespace='assignment')),
    # re_path(r'^media/(?P<path>.*)$', serve,{'document_root':  settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.http import HttpResponse
from django.urls import path
from .views import (
    HomePageView,
    ProfilePageView,
    CreateNewClassView,
    JoinNewClassView,
    NotificationsPageView,
    SettingsPageView,
    ToDoPageView,
)
from .get_or_post_views import (
    NotificationGetOnlyView,
    ProfileChangePostOnlyView,
    ProfileRemovePostOnlyView,
    BioUpdatePostOnlyView,
)

app_name = 'home'

urlpatterns = [
    path('', HomePageView.as_view(), name='home-page'),
    path('create-new/', CreateNewClassView.as_view(), name='create-class'),
    path('join-new/', JoinNewClassView.as_view(), name='join-class'),
    path('todo/', ToDoPageView.as_view(), name='todo-page'),
    path('profile/', ProfilePageView.as_view(), name='profile-page'),
    path('notifications/', NotificationsPageView.as_view(), name='notifications-page'),
    path('settings/', SettingsPageView.as_view(), name='settings-page'),
    path('notifications/get-data/<int:stepCount>/', NotificationGetOnlyView.as_view(), name='notifications-get-only'),
    path('profile/change-profile/', ProfileChangePostOnlyView.as_view(), name='profile-change-post-only'),
    path('profile/remove-profile/', ProfileRemovePostOnlyView.as_view(), name='profile-remove-post-only'),
    path('profile/update-bio/', BioUpdatePostOnlyView.as_view(), name='bio-update-post-only'),
]

classmenu/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
from edusatchel.decorators import classentry_check
from home.models import Class
from django.contrib import messages
from home.send_notifications import (
    after_adding_asignment,
    after_adding_poll,
)

from .backends import (
    validate_urls_files,
    insert_url_and_file_values,
    convert_IST_to_UTC
)

import json
import datetime
import math
from pytz import timezone 

class AccountTypeView(View):
    @classentry_check()
    def get(self, request, *args, **kwargs):
        if request.user.account_type == 'teacher':
            return self.teacher_get(request, *args, **kwargs)
        else:
            return self.student_get(request, *args, **kwargs)

# Create your views here.

class ClassMenuView(View):
    @classentry_check()
    def get(self, request, classID):
        classObj = Class.objects.get(id=classID)
        return render(request, 'classmenu/class.html', {
            'classObj' : classObj,
        })

class ClassSettingsView(AccountTypeView):
    def teacher_get(self, request, classID):
        classObj = Class.objects.get(id=classID)
        return render(request, 'classmenu/settings.html', {
            'classObj' : classObj,
        })

    def student_get(self, request, classID):
        classObj = Class.objects.get(id=classID)
        return render(request, 'classmenu/settings_student.html', {
            'classObj' : classObj,
        })

class AddAssignmentView(View):
    @classentry_check(account_type='teacher')
    def get(self, request, classID):
        classObj = Class.objects.get(id=classID)
        return render(request, 'classmenu/add_assignment.html', {
            'classObj' : classObj,
        })

    @classentry_check(account_type='teacher')
    def post(self, request, classID):
        formPost = request.POST
        formData = request.FILES

        if 'content' in formPost.keys() and 'due-date' in formPost.keys() and 'total-marks' in formPost.keys():
            content = formPost['content'].strip()

            if len(content) <= 5:
                return HttpResponse(json.dumps({'success' : False, 'element' : 'content', 'error_message' : 'Content length should be greater than 5 characters'}))

            dueDate = request.POST['due-date']
            try:
                dueDateTimeObj = datetime.datetime.strptime(dueDate, '%Y-%m-%d %H:%M')
            except:
                return HttpResponse(json.dumps({'success' : False, 'element' : 'dueDate', 'error_message' : 'Due date is a required field'}))
            else:
                if dueDateTimeObj <= datetime.datetime.now():
                    return HttpResponse(json.dumps({'success' : False, 'element' : 'dueDate', 'error_message' : 'Due date and time should be greater than the current datetime'}))

            totalMarks = request.POST['total-marks']
            try:
                totalMarksFloat = float(totalMarks)
                if math.isnan(totalMarksFloat):
                    raise BaseException() 
            except:
                return HttpResponse(json.dumps({'success' : False, 'element' : 'totalMarks', 'error_message' : 'Total mark should be a number'}))
            else:
                if totalMarksFloat <= 0:
                    return HttpResponse(json.dumps({'success' : False, 'element' : 'totalMarks', 'error_message' : 'Total mark should be a positive value.'}))
                elif totalMarksFloat > 1000:
                    return HttpResponse(json.dumps({'success' : False, 'element' : 'totalMarks', 'error_message' : 'Total mark should be lesser than 1000.'}))
                totalMarksFloat = round(totalMarksFloat, 2)


            validatedUrls = validate_urls_files(formPost, formData)   
            if validatedUrls != True:
                return HttpResponse(json.dumps({'success' : False, 'element' : 'attach', 'error_message' : validatedUrls}))

            classObj = Class.objects.get(id=classID)
            urlObjs, fileObjs = insert_url_and_file_values(formPost, formData, classObj, 'assignment')           
            assigObj = classObj.assignment_set.create(
                content = content,
                date_due=convert_IST_to_UTC(dueDateTimeObj),
                total_marks=totalMarksFloat,
            )
            assigObj.files.set(fileObjs)
            assigObj.urls.set(urlObjs)

            after_adding_asignment(classObj, assigObj)
            messages.error(request, 'New assignment added successfully')
            return HttpResponse(json.dumps({'success' : True}))

        return HttpResponse(json.dumps({'success' : False, 'element' : 'alert', 'error_message' : 'Something is wrong. Refresh the page !'}))

class AddPollView(View):
    @classentry_check(account_type='teacher')
    def get(self, request, classID):
        classObj = Class.objects.get(id=classID)
        return render(request, 'classmenu/add_poll.html', {
            'classObj' : classObj,
        })

    @classentry_check(account_type='teacher')
    def post(self, request, classID):
        formPost = request.POST

        if 'title' in formPost.keys() and 'option-1' in formPost.keys() and 'option-2' in formPost.keys() and 'option-3' in formPost.keys() and 'option-4' in formPost.keys() and 'option-5' in formPost.keys():
            title = formPost['title'].strip()

            if len(title) <= 5:
                return HttpResponse(json.dumps({'success' : False, 'element' : 'title', 'error_message' : 'Title length should be greater than 5 characters'}))
            
            allOptions = [formPost['option-1'].strip(), formPost['option-2'].strip(), formPost['option-3'].strip(), formPost['option-4'].strip(), formPost['option-5'].strip()]
            validOptions = []
            for option in allOptions:
                validOptions.append(option) if option else ''
            
            if len(validOptions) < 2:
                return HttpResponse(json.dumps({'success' : False, 'element' : 'option', 'error_message' : 'Atlest two options are required'}))

            classObj = Class.objects.get(id=classID)
            pollObj = classObj.poll_set.create(
                title=title,
            )
            for option in validOptions:
                pollObj.polloption_set.create(
                    content=option,
                )

            after_adding_poll(classObj, pollObj)
            messages.error(request, 'New poll added successfully')
            return HttpResponse(json.dumps({'success' : True}))

        return HttpResponse(json.dumps({'success' : False, 'element' : 'alert', 'error_message' : 'Something is wrong. Refresh the page !'}))

templates/classmenu/add_assignment.html
{% extends 'classmenu/base.html' %}
{% load static %}

{% block title %}{{ classObj.title }}: Add Assignment{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/classmenu/add_assignment.css' %}">
<script src="{% static 'js/classmenu/add_assignment.js' %}"></script>
{% endblock headextraextra %}

{% block bodyextra %}
<div class="content-box">
    <div class="error-div content-error-div"></div>
    <label>Content <span style="color:red;">*</span></label>
    <textarea name="content"></textarea>
    <div class="error-div attach-file-error-div"></div>
    <label>Attach Files/Urls</label>
    <div class="attach-file-parent">
        {% include 'blocks/attach-files.html' %}
    </div>
    <div class="error-div date-error-div"></div>
    <div class="datetime-container">
        <label for="due-date-id">Due Date And Time <span style="color:red;">*</span></label>
        <input type="datetime-local" name="due-date" id="due-date-id">
    </div>
    <div class="error-div marks-error-div"></div>
    <label>Total Marks <span style="color:red;">*</span></label>
    <input type="number" name="total-marks" min="0" max="1000" step="0.01">
    <ul>
        <li>Total mark should be lesser than 1000.</li>
        <li>Total mark should be a positive value.</li>
        <li>Only two decimal places are allowed.</li>
    </ul>
    <button><span>Post</span><div class="spinner"></div></button>
</div>
<script>
    var classIDGlobal = '{{ classObj.id }}';
    var csrftoken = '{{ csrf_token }}';
    var classHomeURL = "{{ classObj.get_url }}";
</script>
{% endblock bodyextra %}

templates/classmenu/add_poll.html
{% extends 'classmenu/base.html' %}
{% load static %}

{% block title %}{{ classObj.title }}: Settings{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/classmenu/add_poll.css' %}">
<script src="{% static 'js/classmenu/add_poll.js' %}"></script>
{% endblock headextraextra %}

{% block bodyextra %}
<div class="content-box">
    <div class="title-box">
        <div class="error-div"></div>
        <label>Title <span style="color:red;">*</span></label>
        <textarea name="title"></textarea>
    </div>
    <div class="option-box">
        <div class="error-div"></div>
        <label>Option 1 <span style="color:red;">*</span></label>
        <input type="text" name="option-1">
        <label>Option 2 <span style="color:red;">*</span></label>
        <input type="text" name="option-2">
        <label>Option 3</label>
        <input type="text" name="option-3">
        <label>Option 4</label>
        <input type="text" name="option-4">
        <label>Option 5</label>
        <input type="text" name="option-5">
    </div>
    <div class="instruction-box">
        <ul>
            <li>Title and two options are required fields</li>
            <li>Option 3, 4 and 5 are optional</li>
            <li>You cannot have more than 5 options</li>
            <li>You wont be able to know the indivitual poll result of a student</li>
            <li>You can see how many students have casted their vote</li>
            <li>Students will also be able to see the result</li>
            <li>Teachers are not allowed to vote</li>
        </ul>
    </div>
    <button><span>Post</span><div class="spinner"></div></button>
</div>
<script>
    var classIDGlobal = '{{ classObj.id }}';
    var csrftoken = '{{ csrf_token }}';
    var classHomeURL = "{{ classObj.get_url }}";
</script>
{% endblock bodyextra %}

templates/classmenu/base.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{% endblock title %}

{% block headextra %}
<link rel='stylesheet' href="{% static 'css/classmenu/base.css' %}">
<script src="{% static 'js/classmenu/base.js' %}"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato&Montserrat&Poppins&Merriweather&Nunito&Roboto">
{% block headextraextra %}
{% endblock headextraextra %}
{% endblock headextra %}

{% block body %}
<div class="back-box">
    <div class="back-button">
        <i class="bi bi-arrow-bar-left"></i>
        <i class="bi bi-house-door"></i>
    </div>
    <div class="more-button">
        <i class="bi bi-three-dots"></i>
    </div>
</div>
<div class="parent-content">
    <div class="nav-bar-box">
        <div class="nav-bar" tabindex="0">
            <div class="item" onclick="directToPage('{{ classObj.get_url }}')">
                <div class="icon-box">
                    <i class="bi bi-collection"></i>
                </div>
                <span>Class</span>
            </div>
            {% if request.user.account_type == 'teacher' %}
                <div class="item" onclick="directToPage('{{ classObj.get_url_add_assignment }}')">
                    <div class="icon-box">
                        <i class="bi bi-journal-arrow-up"></i>
                    </div>
                    <span>Add Assignment</span>
                </div>
                <div class="item" onclick="directToPage('{{ classObj.get_url_add_poll }}')">
                    <div class="icon-box">
                        <i class="bi bi-pie-chart"></i>
                    </div>
                    <span>Add Poll</span>
                </div>
            {% endif %}
            <div class="item" onclick="directToPage('{{ classObj.get_url_settings }}')">
                <div class="icon-box">
                    <i class="bi bi-gear"></i>
                </div>
                <span>Settings</span>
            </div>
            <div class="last-item">
                <i class="bi bi-arrow-right-circle"></i>
            </div>
        </div>
        <div class="nav-puller">
            <i class="bi bi-chevron-right"></i>
        </div>
    </div>
    {% block bodyextra %}
    {% endblock bodyextra %}
</div>
{% block messagespace %}
{% endblock messagespace %}
<script>
    document.body.onload = () => {
        onBaseLoad();
        errorPara = onLoad();
        try {
            onLoadBlock(errorPara);
        } catch(err) {}
    }
    var media_url = '{% get_media_prefix %}';
    var homeURL = "{% url 'home:home-page' %}";
</script>
{% endblock body %}

templates/classmenu/class.html
{% extends 'classmenu/base.html' %}
{% load static %}

{% block title %}{{ classObj.title }}{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/classmenu/class.css' %}">
<link rel='stylesheet' href="{% static 'css/classmenu/class2.css' %}">
<script src="{% static 'js/classmenu/class.js' %}"></script>
<script src="{% static 'js/classmenu/class2.js' %}"></script>
{% endblock headextraextra %}

{% block bodyextra %}
<div class="main-content">
    {% if messages %}
        {% for msg in messages %}
            <div class="message-box item">
                <i class="bi bi-info-circle"></i>
                <span>{{ msg }}</span>
            </div>
        {% endfor %}
    {% endif %}
    <div class="item header">
        <div class="date-box">
            <i class="bi bi-info-circle"></i>
            <div class="popup">Created On</div>
            <span>{{ classObj.formatted_date }}</span>
        </div>
        <h1>{{ classObj.title }}</h1>
    </div>
    <div class="item msg-div">
        <div class="dummy-overlay">
            <img src="{% get_media_prefix %}{{ user.profile_pic_path }}">
            <span>Send a message to the class..</span>
        </div>
        <div class="loading-overlay">
            <div class="spinner"></div>
        </div>
        <div class="real-content">
            <div class="top-bar">
                <p class="error-para"></p>
                <i class="bi bi-x"></i>
            </div>
            <div class="content-box">
                <div class="form">
                    <label>Content..</label>
                    <textarea name='content' maxlength="300"></textarea>
                    <div class="attach-box">
                        {% include 'blocks/attach-files.html' %}
                    </div>
                    <div class="button-box">
                        <button>
                            <i class="bi bi-send"></i>
                            <span>Send</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="all-messages">
        <div class="loading-div">
            <div class="circle">
                <div class="spinner"></div>
            </div>
        </div>
    </div>
</div>
<div class="right-content" tabindex="0">
    <div class="item class-id">
        <div class="header">Class ID</div>
        <div class="id-box">
            <span>{{ classObj.id }}</span>
            <div class="icon-box" title="copy">
                <i class="bi bi-clipboard"></i>
            </div>
        </div>
    </div>
    <div class="item teacher-details">
        <div class="header">Teacher Details</div>
        <div class="sub-box">
            <img src="{% get_media_prefix %}{{ classObj.teacher.profile_pic_path }}"></img>
            <div class="name-box"><p>{{ classObj.teacher.username }}</p></div>
        </div>
        <div class="extra-box">
            <div class="bio-box">{{ classObj.teacher.bio }}</div>
        </div>
        {% if classObj.teacher.bio %}
            <div class="extend-div">
                <i class="bi bi-chevron-compact-down"></i>
            </div>
        {% endif %}
    </div>
    <div class="item class-desc">
        <div class="header">Class Description</div>
        <div class="sub-box">
            <div class="desc-box">{{ classObj.description }}</div>
        </div>
    </div>
</div>
<script>
    var classIDGlobal = '{{ classObj.id }}';
    var csrftoken = '{{ csrf_token }}';
</script>
{% endblock bodyextra %}

templates/classmenu/settings.html
{% extends 'classmenu/base.html' %}
{% load static %}

{% block title %}{{ classObj.title }}: Settings{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/classmenu/settings.css' %}">
<script src="{% static 'js/classmenu/settings.js' %}"></script>
{% endblock headextraextra %}

{% block bodyextra %}
<div class="settings-content">
    <div class="item block-request">
        <span>Block Join Requests</span>
        <div class="switch-container">
            <div class="switch">
                <div class="ball"></div>
            </div>
        </div>
    </div>
    <div class="item class-desc">
        <label>Class Description</label>
        <textarea maxlength="300">{{ classObj.description }}</textarea>
        <div class="error-div"></div>
        <button class="disabled"><span>Save</span><div class="spinner"></div></button>
    </div>
</div>
<div class="item join-req-content">
    <div class="header"><span>Recieved Join Requests</span></div>
    <div class="content-box">
        {% if classObj.get_join_requests %}
            {% for cls_enrollments in classObj.get_join_requests %}
            <div class="item" id="{{ cls_enrollments.encoded_id }}">
                <div class="overlay"></div>
                <span>{{ cls_enrollments.student.username }}</span>
                <div class="accept-button" onclick="asyncFunctionJoinResponse(this, 'accept', '{{ cls_enrollments.encoded_id }}')">Accept</div>
                <div class="decline-button" onclick="asyncFunctionJoinResponse(this, 'decline', '{{ cls_enrollments.encoded_id }}')">Decline</div>
            </div>
            {% endfor %}
        {% else %}
            <div class="empty-div">
                <i class="bi bi-binoculars"></i>
                <span>No Pending Requests</span>
            </div>
        {% endif %}
    </div>
</div>
<div class="item all-students">
    <div class="top-area">All Students</div>
    <div class="bottom-area">
        <div class="search-bar-box">
            <i id="left" class="bi bi-search"></i>
            <i id="right" class="bi bi-x"></i>
            <input type="text">
        </div>
        <div class="content-box">
            <div class="loading-parent">
                <div class="spinner"></div>
            </div>
            <div class="empty-parent">
                <i class="bi bi-emoji-expressionless"></i>
                <span>Empty Result!</span>
            </div>
        </div>
    </div>
</div>
<script>
    var classIDGlobal = '{{ classObj.id }}';
    var csrftoken = '{{ csrf_token }}';
    var classActive = '{{ classObj.active }}';
    var initialClassDesc = '{{ classObj.description }}';
    var classTitle = '{{ classObj.title }}';
</script>
{% endblock bodyextra %}

templates/classmenu/settings_student.html
{% extends 'classmenu/base.html' %}
{% load static %}

{% block title %}{{ classObj.title }}: Settings{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/classmenu/settings_student.css' %}">
<script src="{% static 'js/classmenu/settings_student.js' %}"></script>
{% endblock headextraextra %}

{% block bodyextra %}
<div class="settings-content">
    <div class="item leave-class">
        <span>Leave Class</span>    
        <button><span>Leave</span><div class="spinner"></div></button>
    </div>  
</div>
<script>
    var classIDGlobal = '{{ classObj.id }}';
    var csrftoken = '{{ csrf_token }}';
    var classTitle = '{{ classObj.title }}';
</script>
{% endblock bodyextra %}