edusatchel/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from .views import DefaultView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', DefaultView.as_view()),
    path('admin/', admin.site.urls),
    path('register/', include('register.urls', namespace='register')),
    path('home/', include('home.urls', namespace='home')),
    path('class/', include('classmenu.urls', namespace='classmenu')),
    path('assignment/', include('assignment.urls', namespace='assignment')),
    # re_path(r'^media/(?P<path>.*)$', serve,{'document_root':  settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.http import HttpResponse
from django.urls import path
from .views import (
    HomePageView,
    ProfilePageView,
    CreateNewClassView,
    JoinNewClassView,
    NotificationsPageView,
    SettingsPageView,
    ToDoPageView,
)
from .get_or_post_views import (
    NotificationGetOnlyView,
    ProfileChangePostOnlyView,
    ProfileRemovePostOnlyView,
    BioUpdatePostOnlyView,
)

app_name = 'home'

urlpatterns = [
    path('', HomePageView.as_view(), name='home-page'),
    path('create-new/', CreateNewClassView.as_view(), name='create-class'),
    path('join-new/', JoinNewClassView.as_view(), name='join-class'),
    path('todo/', ToDoPageView.as_view(), name='todo-page'),
    path('profile/', ProfilePageView.as_view(), name='profile-page'),
    path('notifications/', NotificationsPageView.as_view(), name='notifications-page'),
    path('settings/', SettingsPageView.as_view(), name='settings-page'),
    path('notifications/get-data/<int:stepCount>/', NotificationGetOnlyView.as_view(), name='notifications-get-only'),
    path('profile/change-profile/', ProfileChangePostOnlyView.as_view(), name='profile-change-post-only'),
    path('profile/remove-profile/', ProfileRemovePostOnlyView.as_view(), name='profile-remove-post-only'),
    path('profile/update-bio/', BioUpdatePostOnlyView.as_view(), name='bio-update-post-only'),
]

register/urls.py
from django.urls import path
from .views import (
    choose_type_of_account, 
    SignUpTeacherInitialView, 
    SignUpStudentInitialView, 
    SignUpTeacherFinalView, 
    SignUpStudentFinalView,
    LogInView,
    ForgotPasswordView,
    ResetPasswordView,
    ChangePasswordView,
    LogoutView,
)

app_name = 'register'

urlpatterns = [
    path('create/', choose_type_of_account, name='create-account'),
    path('create/teacher/', SignUpTeacherInitialView.as_view(), name="create-teacher"),
    path('create/student/', SignUpStudentInitialView.as_view(), name="create-student"),
    path('teacher/activate-user/<uidb64>/<token>/', SignUpTeacherFinalView.as_view(), name='activate-teacher'),
    path('student/activate-user/<uidb64>/<token>/', SignUpStudentFinalView.as_view(), name='activate-student'),
    path('login/', LogInView.as_view(), name="log-in"),
    path('forgot-password/', ForgotPasswordView.as_view(), name="forgot-password"),
    path('reset-password/<uidb64>/<token>/', ResetPasswordView.as_view(template_name='register/reset_password.html'), name="reset-password"),
    path('change-password/', ChangePasswordView.as_view(), name="change-password"),
    path('logout/', LogoutView.as_view(), name="logout"),
]

home/models.py
from django.db import models
from django.urls import reverse
from register.models import CustomUser
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes

import uuid

# Create your models here.

class Class(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    teacher = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=80, null=False, blank=False)
    description = models.CharField(max_length=300, null=False, blank=False)
    date_started = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    # True means can enter, False means closed

    def __str__(self):
        return f'{self.id} <{self.title}>'

    @property
    def get_url(self):
        return reverse('classmenu:class', kwargs={'classID' : self.id})

    @property
    def get_url_settings(self):
        return reverse('classmenu:settings', kwargs={'classID' : self.id})

    @property
    def get_url_assignments(self):
        return reverse('classmenu:assignments', kwargs={'classID' : self.id})

    @property
    def get_url_add_poll(self):
        return reverse('classmenu:add-poll', kwargs={'classID' : self.id})

    @property
    def get_url_add_assignment(self):
        return reverse('classmenu:add-assignment', kwargs={'classID' : self.id})

    @property
    def formatted_date(self):
        from .backends import check_if_today_or_yesterday
        return check_if_today_or_yesterday(self.date_started)

    @property
    def get_join_requests(self):
        return self.classenrollment_set.filter(enrolled=False)

    @property
    def total_enrolled_students(self):
        return len(self.classenrollment_set.filter(enrolled=True))

    def get_enrolled_students(self):
        return self.classenrollment_set.filter(enrolled=True)

class ClassEnrollment(models.Model):
    class_obj = models.ForeignKey(Class, on_delete=models.CASCADE)
    student = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    enrolled = models.BooleanField(default=False)
    # enrolled will be False when sending join request, it will be made True
    # when teacher accepts it.
    # class will be shown up on home screen only if enrolled is True

    @property
    def encoded_id(self):
        return urlsafe_base64_encode(force_bytes(self.id))

class Notification(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    header = models.CharField(max_length=80, null=False, blank=False)
    body = models.TextField(null=False, blank=False)
    seen = models.BooleanField(default=False)
    time = models.DateTimeField(auto_now_add=True)

home/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View
from classmenu.models import Assignment
from edusatchel.decorators import authentication_check
from assignment.models import Submission


from .send_notifications import (
    after_creating_class,
    after_joining_class,
)
from .backends import (
    validate_new_class,
    validate_join_class,
    get_number_of_unseen_notification,
)

import os

class AccountTypeView(View):
    @authentication_check()
    def get(self, request, *args, **kwargs):
        if request.user.account_type == 'teacher':
            return self.teacher_get(request, *args, **kwargs)
        else:
            return self.student_get(request, *args, **kwargs)

# Create your views here.

class HomePageView(AccountTypeView): 
    def teacher_get(self, request):
        return render(request, 'home/home.html', {
            'header' : 'Classes Created',
            'create_new_title' : 'Create A New Class',
            'url_new' : f"{reverse('home:create-class')}",
            'class_obj_array' : request.user.class_set.all(),
            'notifications' : get_number_of_unseen_notification(request),
        })

    def student_get(self, request):
        return render(request, 'home/home.html', {
            'header' : 'Classes Entrolled',
            'create_new_title' : 'Join A New Class',
            'url_new' : f"{reverse('home:join-class')}",
            'classenrollment_obj_array' : request.user.classenrollment_set.filter(enrolled=True),
            'notifications' : get_number_of_unseen_notification(request),
        })

class ToDoPageView(View):
    def get(self, request):
        returnList = []
        if request.user.isTeacher:
            allSubmissions = Submission.objects.filter(assignment_obj__in=list(Assignment.objects.filter(class_obj__in=list(request.user.class_set.all())))).order_by('date_added')
            for i in allSubmissions:
                if not i.is_corrected:
                    returnList.append([i.student.username, i.assignment_obj.content, i.assignment_obj.class_obj.title, i.get_correct_url, i.assignment_obj.get_correction_url()])
        else:
            allAssignments = Assignment.objects.filter(class_obj__in=list(request.user.get_classes_enrolled())).order_by('date_due')
            for i in allAssignments:
                if not i.is_submitted(request.user):
                    returnList.append([i.class_obj.title, i.content, i.get_ist_date_due, i.get_submit_url()])

        return render(request, 'home/todo.html', {
            'notifications' : get_number_of_unseen_notification(request),
            'allData' : returnList,
        })

class ProfilePageView(View):
    @authentication_check()
    def get(self, request):
        return render(request, 'home/profile.html', {
            'notifications' : get_number_of_unseen_notification(request),
        })
        
class NotificationsPageView(View):
    @authentication_check()
    def get(self, request):
        return render(request, 'home/notifications.html', {
            'notifications' : get_number_of_unseen_notification(request),
        })

class SettingsPageView(View):
    @authentication_check()
    def get(self, request):
        return render(request, 'home/settings.html', {
            'notifications' : get_number_of_unseen_notification(request),
        })

class CreateNewClassView(View):
    @authentication_check(account_type='teacher')
    def get(self, request):
        return render(request, 'home/create_new.html', {
            'notifications' : get_number_of_unseen_notification(request),
        })

    @authentication_check(account_type='teacher')
    def post(self, request):
        returnStatus = validate_new_class(request)

        if returnStatus == True:    
            title = request.POST['title'].strip()
            description = request.POST['description'].strip()
            active = False if 'active' in request.POST.keys() else True
            
            newClassObj = request.user.class_set.create(
                title=title,
                description=description,
                active=active,
            )
            after_creating_class(request.user, newClassObj)
            messages.error(request, 'Class created successfully')
            return redirect(reverse('home:home-page'))

        else:
            return render(request, 'home/create_new.html', {
                'title_error' : returnStatus['title_error'],
                'description_error' : returnStatus['description_error'],
                'general_error' : returnStatus['general_error'],
                'notifications' : get_number_of_unseen_notification(request),
            })

class JoinNewClassView(View):
    @authentication_check(account_type='student')
    def get(self, request):
        return render(request, 'home/join_new.html', {
            'notifications' : get_number_of_unseen_notification(request),
        })

    @authentication_check(account_type='student')
    def post(self, request):
        returnStatus = validate_join_class(request)

        if returnStatus[0] == True:

            request.user.classenrollment_set.create(
                class_obj=returnStatus[1],
            )
            after_joining_class(request.user, returnStatus[1])
            messages.error(request, 'Join Request send successfully')
            return redirect(reverse('home:home-page'))

        else:
            return render(request, 'home/join_new.html', {
                'class_id_error' : returnStatus[1]['class_id_error'],
                'general_error' : returnStatus[1]['general_error'],
                'notifications' : get_number_of_unseen_notification(request),
            })

templates/home/base.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{% endblock title %}

{% block headextra %}
<link rel='stylesheet' href="{% static 'css/home/base.css' %}">
<script src="{% static 'js/home/base.js' %}"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato&Montserrat&Poppins&Merriweather&Nunito">
{% block headextraextra %}
{% endblock headextraextra %}
{% endblock headextra %}

{% block body %}
<div class="nav-bar">
    <div class="content-box" id="home-box">
        <i class="bi bi-house-door"></i>
        <span>Home</span>
    </div>
    <div class="separator"></div>
    <div class="content-box" id="todo-box">
        <i class="bi bi-ui-checks"></i>
        <span>To Do</span>
    </div>
    <div class="separator"></div>
    <div class="content-box" id="profile-box">
        <i class="bi bi-person-circle"></i>
        <span>Profile</span>
    </div>
    <div class="separator"></div>
    <div class="content-box" id="notification-box">
        <i>
            {% if notifications != False %}
            <div class="counter">{{ notifications }}</div>
            {% else %}
            <div class="counter" style="display: none;"></div>
            {% endif %}
            <i class="bi bi-bell"></i>
        </i>
        <span>Notifications</span>
    </div>
    <div class="separator"></div>
    <div class="content-box" id="settings-box">
        <i class="bi bi-gear"></i>
        <span>Settings</span>
    </div>
</div>

{% block messagespace %}
{% endblock messagespace %}

<div class="parent-content">
    {% block bodyextra %}
    {% endblock bodyextra %}
</div>
<script>
    document.body.onload = onBaseLoad();
    var homeURL = "{% url 'home:home-page' %}";
    var todoURL = "{% url 'home:todo-page' %}";
    var profileURL = "{% url 'home:profile-page' %}";
    var notificationsURL = "{% url 'home:notifications-page' %}";
    var settingsURL = "{% url 'home:settings-page' %}";
</script>
{% endblock body %}

templates/home/create_new.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}Create A New Class{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/home/create_new.css' %}">
<script src="{% static 'js/home/create_new.js' %}"></script>
{% endblock headextraextra %}

{% block bodyextra %}
<div class="sub-container">
    <form method="POST" action=".">
        {% csrf_token %}
        {% if general_error %}
            <script>
                alert("{{ general_error }}")
            </script>
        {% endif %}
        <div class="field-parent">
            <label>Title</label>
            <input type="text" name="title" id="id_title" required maxlength="80" minlength="5">
            <div class="error-div">{{ title_error }}</div>
        </div>
        <div class="field-parent">
            <label>Description</label>
            <textarea name="description" id="id_description" required maxlength="300" minlength="5"></textarea>
            <div class="error-div">{{ description_error }}</div>
        </div>
        <input type="checkbox" style="display: none;" id="id_active" name="active">
        <div class="checkbox-custom-container">
            <div class="checkbox"><i class="bi bi-check"></i></div>
            <span>Block join requests</span>
        </div>
        <button>Create</button>
    </form>
    <div class="separator"></div>
    <div class="more-details">
        <div class="list-conatiner">
            <ul>
                <li>Every class will be provided with a unique ID.</li>
                <li>Students will be able to send join request using that ID.</li>
                <li>Students are allowed to join the class if the teacher accepts the request.</li>
                <li>These requests will be shown up in the notifications</li>
                <li>You can restrict students from sending join requests by checking 'Block join requests'.</li>
                <li>You can change it later from the settings if needed.</li>
            </ul>
        </div>
    </div>
</div>
<script>
    document.body.onload = onLoad();
</script>
{% endblock bodyextra %}

templates/home/home.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/home/home.css' %}">
<script src="{% static 'js/home/home.js' %}"></script>
{% endblock headextraextra %}

{% block messagespace %}
    {% if messages %}
        {% for msg in messages %}
            <style>
                body > .parent-content {
                    height: calc(100% - 140px);
                }
                @media (max-width:415px) {
                    body > .message-div {
                        height: 70px;
                    }
                    body > .parent-content {
                        height: calc(100% - 160px);
                    }
                }
            </style>
            <div class="message-div">
                <i class="bi bi-info-circle-fill"></i>
                <p>{{ msg }}</p>
            </div>
        {% endfor %}
    {% endif %}
{% endblock messagespace %}

{% block bodyextra %}
<div class="header-container">
    <h1>{{ header }}</h1>
</div>
<div class="main-content">
    <div class="class-box create-new" onclick="location.href = '{{ url_new }}'">
        <div class="horizontal-line"></div>
        <div class="vertical-line"></div>
        <div class="icon-container">
            <i class="bi bi-plus"></i>
        </div>
        <div class="text-area">{{ create_new_title }}</div>
    </div>
    {% if class_obj_array %}
        {% for class_obj in class_obj_array %}
            <div class="class-box">
                <div class="title-container">
                    <p>{{ class_obj.title }}</p>
                    <div class="popup" tabindex='1'>{{ class_obj.title }}</div>
                </div>
                <div class="horizontal-line one"></div>
                <div class="horizontal-line two"></div>
                <span class="teacher-name">{{ class_obj.teacher.username }}</span>
                <div class="redirect-butt" onclick="location.href = '{{ class_obj.get_url }}'">
                    <i class="bi bi-chevron-double-right"></i>
                </div>
            </div>
            {% endfor %}
            {% elif classenrollment_obj_array %}
            {% for classenrollment_obj in classenrollment_obj_array %}
            <div class="class-box">
                <div class="title-container">
                    <p>{{ classenrollment_obj.class_obj.title }}</p>
                    <div class="popup" tabindex='1'>{{ classenrollment_obj.class_obj.title }}</div>
                </div>
                <div class="horizontal-line one"></div>
                <div class="horizontal-line two"></div>
                <span class="teacher-name">{{ classenrollment_obj.class_obj.teacher.username }}</span>
                <div class="redirect-butt" onclick="location.href = '{{ classenrollment_obj.class_obj.get_url }}'">
                    <i class="bi bi-chevron-double-right"></i>
                </div>
            </div>
        {% endfor %}
    {% endif %}
</div>
<script>
    document.body.onload = onLoad();
</script>
{% endblock bodyextra %}

templates/home/join_new.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}Join Class{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/home/create_new.css' %}">
<link rel='stylesheet' href="{% static 'css/home/join_new.css' %}">
<script src="{% static 'js/home/join_new.js' %}"></script>
{% endblock headextraextra %}

{% block bodyextra %}
<div class="sub-container">
    <form method="POST" action=".">
        {% csrf_token %}
        {% if general_error %}
            <script>
                alert("{{ general_error }}")
            </script>
        {% endif %}
        <div class="field-parent">
            <label>Class ID</label>
            <input type="text" name="class_id" id="id_class_id" required autocomplete="off">
            <div class="error-div">{{ class_id_error }}</div>
        </div>
        <button>Request Join</button>
    </form>
    <div class="separator"></div>
    <div class="more-details">
        <div class="list-conatiner">
            <ul>
                <li>A Join Request will be send to the teacher</li>
                <li>You will be admitted as soon as the teacher accepts the request</li>
            </ul>
        </div>
    </div>
</div>
<script>
    document.body.onload = onLoad();
</script>
{% endblock bodyextra %}

templates/home/notifications.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}Notifications{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/home/notifications.css' %}">
<script src="{% static 'js/home/notifications.js' %}"></script>
{% endblock headextraextra %}

{% block bodyextra %}
<div class="no-network-box">
    <i class="bi bi-wifi-off"></i>
    <p>No Network Connection</p>
    <button onclick="location.href = '/home/notifications/'">Retry</button>
</div>
<div class="no-notifications-box">
    <i class="bi bi-bell-slash"></i>
    <p>Empty Notifications</p>
</div>
<div class="left-content"></div>
<div class="right-content">
    <div class="content-box">
        <div class="header"></div>
        <div class="content"></div>
        <div class="date-box">
            <i class="bi bi-asterisk"></i>
            <div class="time"></div>
            <div class="date"></div>
        </div>
    </div>
</div>
<div class="small-content"></div>
<script>
    document.body.onload = onLoad();
</script>
{% endblock bodyextra %}

templates/home/profile.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}Profile{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/home/profile.css' %}">
<script src="{% static 'js/home/profile.js' %}"></script>
{% endblock headextraextra %}

{% block bodyextra %}
<div class="top-box">
    <div class="profile-holder">
        <div class="loading-box">
            <div class="spinner"></div>
        </div>
        <img src="{% get_media_prefix %}{{ user.profile_pic_path }}">
        <div class="popup-box">
            <i class="bi bi-pencil"></i>
            <label><input disabled type="file" style="display: none; position: fixed; top: -100px;" name="profile_pic" id="profile_pic_id" accept="image/*"><div class="row-one">Change Profile</div></label>
            <label><div class="row-two">Remove Profile</div></label>
        </div>
    </div>
    <p class="error"></p>
</div>
<div class="extra-box">
    <div class="content-box">
        {% if user.account_type == 'teacher' %}
            <style>
                .parent-content > .extra-box > .content-box  {
                    grid-template-areas: 'bio bio username'
                        'bio bio account';
                }
            </style>
            <div class="bio-box">
                <div class="spinner"></div>
                <label>Bio</label>
                <textarea maxlength="300">{{ user.bio }}</textarea>
                <button class="disabled">Save</button>
            </div>
        {% endif %}
        <div class="username-box">
            <div class="header">Username</div>
            <div class="ball"></div>
            <span>{{ user.username }}</span>
        </div>
        <div class="account-type-box">
            <div class="header">Account Type</div>
            <div class="ball"></div>
            <span>{{ user.account_type|capfirst }}</span>
        </div>
    </div>
</div>
<script>
    var csrftoken = "{{ csrf_token }}";
    var initialBio = "{{ user.bio }}";
    var accountType = "{{ user.account_type }}";
    document.body.onload = onLoad();
</script>
{% endblock bodyextra %}

templates/home/settings.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}Settings{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/home/settings.css' %}">
<script src="{% static 'js/home/settings.js' %}"></script>
{% endblock headextraextra %}

{% block bodyextra %}
<div class="content-small with-icon">
    <div class="icon-box">
        <i class="bi bi-key"></i>
    </div>
    <div class="title-box">
        <p>Change Password</p>
    </div>
    <div class="button-box">
        <div class="button" onclick=redirect("{% url 'register:change-password' %}")><i class="bi bi-caret-right"></i></div>
    </div>
</div>
<div class="content-small with-icon">
    <div class="icon-box">
        <i class="bi bi-box-arrow-right"></i>
    </div>
    <div class="title-box">
        <p>Logout</p>
    </div>
    <div class="button-box">
        <div class="button" onclick=redirect("{% url 'register:logout' %}")><i class="bi bi-caret-right"></i></div>
    </div>
</div>
<!-- Need to add delete account. In the future.. -->
<script>
    document.body.onload = onLoad();
</script>
{% endblock bodyextra %}

templates/home/todo.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}To Do{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/home/todo.css' %}">
<script src="{% static 'js/home/todo.js' %}"></script>
{% endblock headextraextra %}

{% block bodyextra %}
<div class="header-container">
    <div class="timeline-part">
        <div class="icon-box">
            <i class="bi bi-ui-checks"></i>
        </div>
        <div class="line"></div>
    </div>
    <div class="content-part">
        <div class="content">To Do List..</div>
    </div>
</div>
{% if allData %}
    {% if request.user.isTeacher %}
        <div class="notice-container">
            <div class="timeline-part">
                <div class="icon-box">
                    <i class="bi bi-exclamation"></i>
                </div>
                <div class="line"></div>
            </div>
            <div class="content-part">
                <div class="content">Sorted by date of submission</div>
            </div>
        </div>
        {% for studentName, assignmentTitle, classTitle, correctionUrl, assignmentUrl in allData %}
            <div class="details-container">
                <div class="timeline-part">
                    <div class="icon-box" onclick="openURL('{{ correctionUrl }}')">
                        <i id="normal" class="bi bi-journals"></i>
                        <i id="hover" class="bi bi-chevron-double-right"></i>
                    </div>
                    <div class="line"></div>
                </div>
                <div class="content-part">
                    <div class="content">
                        <div class="top-area">In {{ classTitle }}</div>
                        <div class="bottom-area">
                            Review the submission from the student <span>{{ studentName }}</span> for the assignment <span class="link" onclick="openURL('{{ assignmentUrl }}')">{{ assignmentTitle }}</span><br>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="notice-container">
            <div class="timeline-part">
                <div class="icon-box">
                    <i class="bi bi-exclamation"></i>
                </div>
                <div class="line"></div>
            </div>
            <div class="content-part">
                <div class="content">Sorted by due date of assignments</div>
            </div>
        </div>
        {% for classTitle, assignmentContent, assignmentDueDate, submitUrl in allData %}
            <div class="details-container">
                <div class="timeline-part">
                    <div class="icon-box" onclick="openURL('{{ submitUrl }}')">
                        <i id="normal" class="bi bi-journals"></i>
                        <i id="hover" class="bi bi-chevron-double-right"></i>
                    </div>
                    <div class="line"></div>
                </div>
                <div class="content-part">
                    <div class="content">
                        <div class="top-area">In {{ classTitle }}</div>
                        <div class="bottom-area">
                            Submit the assignment <span>{{ assignmentContent }}</span> with the due date <span>{{ assignmentDueDate }}</span><br>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% else %}
    <div class="completed-container">
        <div class="timeline-part">
            <div class="icon-box">
                <i class="bi bi-check-all"></i>
            </div>
            <div class="line"></div>
        </div>
        <div class="content-part">
            <div class="content">
                You have completed all the work..
            </div>
        </div>
    </div>
{% endif %}
<div class="end-container">
    <div class="timeline-part">
        <div class="icon-box">
        </div>
        <div class="line"></div>
    </div>
    <div class="content-part"></div>
</div>
<script>
    document.body.onload = onLoad();
</script>
{% endblock bodyextra %}