edusatchel/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from .views import DefaultView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', DefaultView.as_view()),
    path('admin/', admin.site.urls),
    path('register/', include('register.urls', namespace='register')),
    path('home/', include('home.urls', namespace='home')),
    path('class/', include('classmenu.urls', namespace='classmenu')),
    path('assignment/', include('assignment.urls', namespace='assignment')),
    # re_path(r'^media/(?P<path>.*)$', serve,{'document_root':  settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.http import HttpResponse
from django.urls import path
from .views import (
    HomePageView,
    ProfilePageView,
    CreateNewClassView,
    JoinNewClassView,
    NotificationsPageView,
    SettingsPageView,
    ToDoPageView,
)
from .get_or_post_views import (
    NotificationGetOnlyView,
    ProfileChangePostOnlyView,
    ProfileRemovePostOnlyView,
    BioUpdatePostOnlyView,
)

app_name = 'home'

urlpatterns = [
    path('', HomePageView.as_view(), name='home-page'),
    path('create-new/', CreateNewClassView.as_view(), name='create-class'),
    path('join-new/', JoinNewClassView.as_view(), name='join-class'),
    path('todo/', ToDoPageView.as_view(), name='todo-page'),
    path('profile/', ProfilePageView.as_view(), name='profile-page'),
    path('notifications/', NotificationsPageView.as_view(), name='notifications-page'),
    path('settings/', SettingsPageView.as_view(), name='settings-page'),
    path('notifications/get-data/<int:stepCount>/', NotificationGetOnlyView.as_view(), name='notifications-get-only'),
    path('profile/change-profile/', ProfileChangePostOnlyView.as_view(), name='profile-change-post-only'),
    path('profile/remove-profile/', ProfileRemovePostOnlyView.as_view(), name='profile-remove-post-only'),
    path('profile/update-bio/', BioUpdatePostOnlyView.as_view(), name='bio-update-post-only'),
]

register/urls.py
from django.urls import path
from .views import (
    choose_type_of_account, 
    SignUpTeacherInitialView, 
    SignUpStudentInitialView, 
    SignUpTeacherFinalView, 
    SignUpStudentFinalView,
    LogInView,
    ForgotPasswordView,
    ResetPasswordView,
    ChangePasswordView,
    LogoutView,
)

app_name = 'register'

urlpatterns = [
    path('create/', choose_type_of_account, name='create-account'),
    path('create/teacher/', SignUpTeacherInitialView.as_view(), name="create-teacher"),
    path('create/student/', SignUpStudentInitialView.as_view(), name="create-student"),
    path('teacher/activate-user/<uidb64>/<token>/', SignUpTeacherFinalView.as_view(), name='activate-teacher'),
    path('student/activate-user/<uidb64>/<token>/', SignUpStudentFinalView.as_view(), name='activate-student'),
    path('login/', LogInView.as_view(), name="log-in"),
    path('forgot-password/', ForgotPasswordView.as_view(), name="forgot-password"),
    path('reset-password/<uidb64>/<token>/', ResetPasswordView.as_view(template_name='register/reset_password.html'), name="reset-password"),
    path('change-password/', ChangePasswordView.as_view(), name="change-password"),
    path('logout/', LogoutView.as_view(), name="logout"),
]

register/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes

import uuid

ACCOUNT_TYPES = (
    ('student','Student'),
    ('teacher', 'Teacher'),
)
def get_image_upload_location(self, filename):    
    return f"profile/{self.image_storage_id}/image.{filename.split('.')[-1]}"

class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, password, account_type):
        if not email:
            raise ValueError("User must have an email address.")
        if not username:
            raise ValueError("User must have a username.")
        if not account_type:
            raise ValueError("User must have a account_type.")
        user = self.model(
            email=self.normalize_email(email),
            username=username,
            account_type=account_type,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password, account_type):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
            account_type=account_type,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.is_email_verified = True
        user.save(using=self._db)
        return user

# Create your models here.

class CustomUser(AbstractBaseUser):

    email = models.EmailField(verbose_name='email', max_length=254, unique=True) 
    username = models.CharField(max_length=30, unique=False)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True) 
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False) 
    is_active = models.BooleanField(default=True) 
    is_staff = models.BooleanField(default=False) 
    is_superuser = models.BooleanField(default=False) 
    account_type = models.CharField(max_length=7, choices=ACCOUNT_TYPES, blank=False, null=False)
    profile_pic = models.ImageField(blank=True, upload_to=get_image_upload_location, default='profile/default.jpg')
    bio = models.TextField(max_length=300, null=True, blank=True)
    is_email_verified = models.BooleanField(default=False)
    image_storage_id = models.UUIDField(default=uuid.uuid4, editable=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'account_type']

    def __str__(self):
        return f'{self.email} <{self.account_type}>'

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

    @property
    def encoded_id(self):
        return urlsafe_base64_encode(force_bytes(self.id))

    @property
    def profile_pic_path(self):
        return f'{self.profile_pic}'

    @property
    def isTeacher(self):
        if self.account_type == 'teacher':
            return True
        return False

    def get_classes_enrolled(self):
        if not self.isTeacher:
            return [i.class_obj for i in self.classenrollment_set.filter(enrolled=True)]

register/forms.py
from django.contrib.auth.forms import SetPasswordForm
from django.core.exceptions import ValidationError
from django import forms

class CustomSetPasswordForm(SetPasswordForm):

    error_messages = {
        'general_error': 'Something went wrong. Refresh the page ?',
        'password_mismatch': 'The two password fields didn’t match.',
        'password_less_characters': 'Password should contain atleast 8 characters',
    }

    new_password1 = forms.CharField(
        label="New password",
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        strip=False,
    )

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
            if len(password1) < 8:
                raise ValidationError(
                    self.error_messages['password_less_characters'],
                    code='password_less_characters',
                )
        else:
            raise ValidationError(
                self.error_messages['general_error'],
                code='general_error',
            )

        return password2

templates/register/base.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{% endblock title %}

{% block headextra %}
<link rel='stylesheet' href="{% static 'css/register/base.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato&Montserrat&Poppins">
{% block headextraextra %}
{% endblock headextraextra %}
{% endblock headextra %}

{% block body %}
<i class="bi bi-journals" id="book"></i>
<i class="bi bi-trophy" id="trophy"></i>
<i class="bi bi-bar-chart-fill" id="graph"></i>
<i class="bi bi-calculator" id="calc"></i>
{% block bodyextra %}
{% endblock bodyextra %}
{% endblock body %}

templates/register/change_password.html
{% extends 'register/base.html' %}
{% load static %}

{% block title %}Change Password{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/register/change_password.css' %}">
<script src="{% static 'js/register/change_password.js' %}"></script>
{% endblock headextraextra %}

{% block bodyextra %}
<div class="parent">
    <div class="header-container">
        <h1>Change Password</h1>
    </div>
    <form method="POST" action='.'>
        {% csrf_token %}
        {% if general_error %}
            <script>
                alert("{{ general_error }}")
            </script>
        {% endif %}
        <div class="field-parent">
            <input type="password" name="old_password" autocomplete="password" required id="id_old_password">
            <label>Old Password</label>
            <div class="error-div">{{ old_pass_error }}</div>
        </div>
        <div class="field-parent">
            <input type="password" name="new_password1" autocomplete="password" required id="id_new_password1">
            <label>New Password</label>
            <div class="error-div">{{ new_pass_error }}</div>
        </div>
        <div class="field-parent">
            <input type="password" name="new_password2" autocomplete="password" required id="id_email">
            <label>Password Confirmation</label>
        </div>
        <button>Change</button>
    </form>
</div>
<script>
    document.body.onload = onLoad();
</script>
{% endblock bodyextra %}

templates/register/create.html
{% extends 'register/base.html' %}
{% load static %}

{% block title %}Types of Account{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/register/create.css' %}">
<script src="{% static 'js/register/create.js' %}"></script>
{% endblock headextraextra %}

{% block bodyextra %}
<div class='header-container'>
    <h1>Types of Account</h1>
</div>
<div class="content-box">
    <div class="card-box">
        <img src="{% get_media_prefix %}source/register/teacher.png">
        <div class="header">Teacher</div>
        <ul>
            <li>Can start courses</li>
            <li>Can provide assignments</li>
            <li>Can monitor the activities of their students</li>
        </ul>
        <div class="button-box">
            <div class="button-bg" id="teacher">
                <button>CREATE</button>
            </div>
        </div>
    </div>
    <div class="card-box">
        <img src="{% get_media_prefix %}source/register/student.png">
        <div class="header">Student</div>
        <ul>
            <li>Can entroll in the courses</li>
            <li>Can submit assignments</li>
        </ul>
        <div class="button-box">
            <div class="button-bg" id="student">
                <button>CREATE</button>
            </div>
        </div>
    </div>
</div>
<script>
    var teacherRedirect = "{% url 'register:create-teacher' %}";
    var studentRedirect = "{% url 'register:create-student' %}";
    document.body.onload = onLoad();
</script>
{% endblock bodyextra %}

templates/register/create_final.html
{% extends 'register/base.html' %}
{% load static %}

{% block title %}Choose The Account Type{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/register/create_final.css' %}">
<script src="{% static 'js/register/create_final.js' %}"></script>
{% endblock headextraextra %}

{% block bodyextra %}
<div class="parent">
    {% include 'register/blocks/progress_line.html' %}
    <form method="POST" action="." enctype="multipart/form-data">
        {% csrf_token %}
        {% if general_error %}
            <script>
                alert("{{ general_error }}")
            </script>
        {% endif %}
        <div class="profile-container">
            <div class="error-div">{{ profile_error }}</div>
            <div class="image-container">
                <img style="background-image: url('/media/profile/default.jpg');"></img>
                <div class="check-overlay">
                    <i class="bi bi-check2"></i>
                </div>
            </div>
            <label for='profile_pic_id'>
                <i class="bi bi-cloud-arrow-up-fill"></i>
                <p>Upload profile</p>
            </label>
            <div class="remove-butt">Remove</div>
            <input type="file" name="profile_pic" id="profile_pic_id" accept="image/*">
        </div>
        <div class="field-parent">
            <textarea name="bio" id="id_email" required maxlength="300"></textarea>
            <label>Bio</label>
            <div class="error-div">{{ bio_error }}</div>
        </div>
        <button>SignUp</button>
    </form>
    <div class="separator"></div>
    <div class="confirmation-container">
        <i class="bi bi-check-circle-fill"></i>
        <p>Verification completed</p>
    </div>
</div>
<script>
    document.body.onload = onLoad();
</script>
{% endblock bodyextra %}

templates/register/create_initial.html
{% extends 'register/base.html' %}
{% load static %}

{% block title %}Create Account{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/register/create_initial.css' %}">
{% endblock headextraextra %}

{% block bodyextra %}
<div class="parent">
    {% if messages %}
        {% for msg in messages %}
            <div class="message-div">
                <i class="bi bi-info-circle-fill"></i>
                <p>{{ msg }}</p>
            </div>
        {% endfor %}
    {% endif %}
    {% include 'register/blocks/progress_line.html' %}
    <div class="header-container">
        <h1>Sign Up</h1>
        <p>As {{ account_for }}</p>
    </div>
    <form method="POST" action=".">
        {% csrf_token %}
        {% if general_error %}
            <script>
                alert("{{ general_error }}")
            </script>
        {% endif %}
        <div class="field-parent">
            <input type="email" name="email" autocapitalize="none" autocomplete="email" required id="id_email" value="{{ latest_email }}">
            <label>Email</label>
            <div class="error-div">{{ email_error }}</div>
        </div>
        <div class="field-parent">
            <input type="text" name="username" maxlength="30" autocapitalize="none" autocomplete="username" required id="id_username" value="{{ latest_username }}">
            <label>Name</label>
            <div class="error-div">{{ username_error }}</div>
        </div>
        <div class="field-parent">
            <input type="password" name="password1" autocomplete="new-password" required id="id_password1">
            <label>Password</label>
            <div class="error-div">{{ password_error }}</div>
        </div>
        <div class="field-parent conf-pass-box">
            <input type="password" name="password2" autocomplete="new-password" required id="id_password2">
            <label>Confirm Password</label>
        </div>
        <div class="button-container">
            <p>Already a user? <a href="{% url 'register:log-in' %}">Log In</a></p>
            <button>NEXT</button>
        </div>
    </form>
</div>
<script src="{% static 'js/register/create_initial.js' %}" onload="onLoad()"></script>
{% endblock bodyextra %}

templates/register/create_student_final.html
{% extends 'register/base.html' %}
{% load static %}

{% block title %}Extra Details{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/register/create_final.css' %}">
{% endblock headextraextra %}

{% block bodyextra %}
<div class="parent">
    {% include 'register/blocks/progress_line.html' %}
    <form method="POST" action="." enctype="multipart/form-data">
        {% csrf_token %}
        <div class="profile-container">
            <div class="error-div">{{ profile_error }}</div>
            <div class="image-container">
                <img style="background-image: url('{% get_media_prefix %}profile/default.jpg');"></img>
                <div class="check-overlay">
                    <i class="bi bi-check2"></i>
                </div>
            </div>
            <label for='profile_pic_id'>
                <i class="bi bi-cloud-arrow-up-fill"></i>
                <p>Upload profile</p>
            </label>
            <div class="remove-butt">Remove</div>
            <input type="file" name="profile_pic" id="profile_pic_id" accept="image/*">
        </div>
        <button>SignUp</button>
    </form>
    <div class="separator"></div>
    <div class="confirmation-container">
        <i class="bi bi-check-circle-fill"></i>
        <p>Verification completed</p>
    </div>
</div>
<script src="{% static 'js/register/create_final.js' %}" onload="onLoadStudent()"></script>
{% endblock bodyextra %}

templates/register/create_teacher.html
{% extends 'register/base.html' %}
{% load static %}

{% block title %}Choose The Account Type{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/register/create_teacher.css' %}">
<script src="{% static 'js/register/create_teacher.js' %}"></script>
{% endblock headextraextra %}

{% block bodyextra %}
<div class="parent">
    {% include 'register/blocks/progress_line.html' %}
    <div class="header-container">
        <h1>Sign Up</h1>
        <p>As Teacher</p>
    </div>
    <form method="POST" action=".">
        {% csrf_token %}
        {% if general_error %}
            <script>
                const confirmation = window.confirm('{{ general_error }}');
                if (confirmation) {
                    location.href = "{% url 'create-teacher' %}"; 
                }
            </script>
        {% endif %}
        <div class="field-parent">
            <input type="email" name="email" autocapitalize="none" autocomplete="email" required id="id_email" value="{{ latest_email }}">
            <label>Email</label>
            <div class="error-div">{{ email_error }}</div>
        </div>
        <div class="field-parent">
            <input type="text" name="username" maxlength="30" autocapitalize="none" autocomplete="username" required id="id_username" value="{{ latest_username }}">
            <label>Name</label>
            <div class="error-div">{{ username_error }}</div>
        </div>
        <div class="field-parent">
            <input type="password" name="password1" autocomplete="new-password" required id="id_password1">
            <label>Password</label>
            <div class="error-div">{{ password_error }}</div>
        </div>
        <div class="field-parent">
            <input type="password" name="password2" autocomplete="new-password" required id="id_password2">
            <label>Confirm Password</label>
        </div>
        <div class="button-container">
            <a href="{% url 'log-in' %}">Log In</a>
            <button>NEXT</button>
        </div>
    </form>
</div>
<script>
    document.body.onload = onLoad();
</script>
{% endblock bodyextra %}

templates/register/forgot-pass.html
{% extends 'register/base.html' %}
{% load static %}

{% block title %}Forgot Password{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/register/forgot-pass.css' %}">
<script src="{% static 'js/register/forgot-pass.js' %}"></script>
{% endblock headextraextra %}

{% block bodyextra %}
<div class="parent">
    <form method="POST" action='.'>
        {% csrf_token %}
        {% if general_error %}
            <script>
                alert("{{ general_error }}")
            </script>
        {% endif %}
        <input type="email" name="email" autocomplete="email" maxlength="254" required id="id_email">
        <p style="color: white;">{{ error }}</p>
        <button>Log In</button>
    </form>
</div>
<script>
    document.body.onload = onLoad();
</script>
{% endblock bodyextra %}

templates/register/forgot_pass.html
{% extends 'register/base.html' %}
{% load static %}

{% block title %}Request Password Reset{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/register/forgot_pass.css' %}">
<script src="{% static 'js/register/forgot_pass.js' %}"></script>
{% endblock headextraextra %}

{% block bodyextra %}
<div class="parent">
    <div class="header-container">
        <h1>Request Password Reset</h1>
    </div>
    <form method="POST" action='.'>
        {% csrf_token %}
        {% if general_error %}
            <script>
                alert("{{ general_error }}")
            </script>
        {% endif %}
        <div class="field-parent">
            <input type="email" name="email" autocomplete="email" maxlength="254" required id="id_email">
            <label>Email</label>
            <div class="error-div">{{ error }}</div>
        </div>
        <button>Request</button>
    </form>
</div>
<script>
    document.body.onload = onLoad();
</script>
{% endblock bodyextra %}

templates/register/log_in.html
{% extends 'register/base.html' %}
{% load static %}

{% block title %}Log In{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/register/log_in.css' %}">
<script src="{% static 'js/register/log_in.js' %}"></script>
{% endblock headextraextra %}

{% block bodyextra %}
<div class="parent">
    {% if messages %}
        <style>
            .parent {
                padding-top: 10px;
            }
        </style>
        {% for msg in messages %}
            <div class="message-div">
                <i class="bi bi-info-circle-fill"></i>
                <p>{{ msg }}</p>
            </div>
            <div class="separator"></div>
        {% endfor %}
    {% endif %}
    <div class="header-container">
        <h1>Log In</h1>
    </div>
    <form method="POST" action='.'>
        {% csrf_token %}
        {% if general_error %}
            <script>
                alert("{{ general_error }}")
            </script>
        {% endif %}
        <div class="field-parent">
            <input type="email" name="email" autocapitalize="none" autocomplete="email" required id="id_email" value="{{ latest_email }}">
            <label>Email</label>
            <div class="error-div">{{ error_details }}</div>
        </div>
        <div class="field-parent">
            <input type="password" name="password" autocomplete="password" required id="id_password">
            <label>Password</label>
            <div class="forgot-pass-div"><a href="{% url 'register:forgot-password' %}">Forgot Password ?</a></div>
            <div class="eye-container">
                <i class="bi bi-eye"></i>
                <div class="cut-line"></div>
            </div>
        </div>
        <div class="button-container">
            <p>Don't have an account? <a href="{% url 'register:create-account' %}">Sign Up</a></p>
            <button>Log In</button>
        </div>
    </form>
</div>
<script>
    document.body.onload = onLoad();
</script>
{% endblock bodyextra %}

templates/register/logout.html
{% extends 'register/base.html' %}
{% load static %}

{% block title %}Log In{% endblock title %}

{% block headextraextra %}
<style>
    .parent {
        width: 450px;
        height: fit-content;
        background-color: var(--primary-color);
        box-shadow: 0 0 10px var(--shadow-color);
        border-radius: 15px;
        padding: 20px 0;
    }
    .parent > form {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        margin: 20px 0;
        margin-top: 10px;
        width: 100%;
        padding: 0 20px;
    }
    .parent > form > p {
        color: var(--secondary-lighter-color); 
        font-family: Verdana, Geneva, Tahoma, sans-serif; 
        width: 100%;
        font-size: 16px; 
        text-align: center;
        word-break: break-all;
    }
    .parent > form > p > span {
        font-size: 18px; 
        font-weight: bold;
    }
    .parent > form > button {
        margin-top: 10px;
        padding: 8px 12px;
        font-family: "Montserrat", Verdana, Geneva, Tahoma, sans-serif;
        font-size: 16px;
        border-radius: 8px;
        border: 1px solid var(--tertiary-color);
        outline: none;
        background-color: transparent;
        cursor: pointer;
        color: var(--tertiary-color);
        transition: color 0.3s, background-color 0.3s;
    }
    .parent > form > button:hover {
        color: white;
        background-color: var(--tertiary-color);
    }
</style>
{% endblock headextraextra %}

{% block bodyextra %}
<div class="parent">
    <form method="POST" action='.'>
        {% csrf_token %}
        <p>Username : <span>{{ request.user.username }}</span></p>
        <button>Logout</button>
    </form>
</div>
{% endblock bodyextra %}

templates/register/reset-pass-send.html
{% extends 'register/base.html' %}
{% load static %}

{% block title %}Password Reset Email Send{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/register/reset-pass-send.css' %}">
{% endblock headextraextra %}

{% block bodyextra %}
<div class="parent">
    <p style="color: white;">An email has been send to <span style="color: var(--secondary-light-color);">{{ to_email }}</span> reset your password</p>
</div>
<script>
    document.body.onload = onLoad();
</script>
{% endblock bodyextra %}

templates/register/reset_pass_send.html
{% extends 'register/base.html' %}
{% load static %}

{% block title %}Password Reset Email Send{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/register/reset_pass_send.css' %}">
{% endblock headextraextra %}

{% block bodyextra %}
<div class="parent">
    <div class="content-container">
        <i class="bi bi-envelope-dash"></i>
        <h2>An email has been send to <span>{{ to_email }}</span> for resetting your password.</h2>
    </div>
</div>
{% endblock bodyextra %}

templates/register/reset_password.html
{% extends 'register/base.html' %}
{% load static %}

{% block title %}Choose A New Password{% endblock title %}

{% block headextraextra %}
<link rel='stylesheet' href="{% static 'css/register/reset_password.css' %}">
<script src="{% static 'js/register/reset_password.js' %}"></script>
{% endblock headextraextra %}

{% block bodyextra %}
<div class="parent">
    <div class="header-container">
        <h1>Choose A New Password</h1>
    </div>
    <form method="POST" action='.' style="color: white;">
        {% csrf_token %}
        {% if general_error %}
            <script>
                alert("{{ general_error }}")
            </script>
        {% endif %}
        <div class="field-parent">
            <input type="password" name="new_password1" autocomplete="new-password" required="" id="id_new_password1" minlength="8">
            <label>Password</label>
            <div class="error-div">{{ error }}</div>
        </div>
        <div class="field-parent">
            <input type="password" name="new_password2" autocomplete="new-password" required="" id="id_new_password2" minlength="8">
            <label>Password Confirmation</label>
        </div>
        <button>Confirm</button>
    </form>
</div>
<script>
    document.body.onload = onLoad();
</script>
{% endblock bodyextra %}