edusatchel/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from .views import DefaultView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', DefaultView.as_view()),
    path('admin/', admin.site.urls),
    path('register/', include('register.urls', namespace='register')),
    path('home/', include('home.urls', namespace='home')),
    path('class/', include('classmenu.urls', namespace='classmenu')),
    path('assignment/', include('assignment.urls', namespace='assignment')),
    # re_path(r'^media/(?P<path>.*)$', serve,{'document_root':  settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.http import HttpResponse
from django.urls import path
from .views import (
    HomePageView,
    ProfilePageView,
    CreateNewClassView,
    JoinNewClassView,
    NotificationsPageView,
    SettingsPageView,
    ToDoPageView,
)
from .get_or_post_views import (
    NotificationGetOnlyView,
    ProfileChangePostOnlyView,
    ProfileRemovePostOnlyView,
    BioUpdatePostOnlyView,
)

app_name = 'home'

urlpatterns = [
    path('', HomePageView.as_view(), name='home-page'),
    path('create-new/', CreateNewClassView.as_view(), name='create-class'),
    path('join-new/', JoinNewClassView.as_view(), name='join-class'),
    path('todo/', ToDoPageView.as_view(), name='todo-page'),
    path('profile/', ProfilePageView.as_view(), name='profile-page'),
    path('notifications/', NotificationsPageView.as_view(), name='notifications-page'),
    path('settings/', SettingsPageView.as_view(), name='settings-page'),
    path('notifications/get-data/<int:stepCount>/', NotificationGetOnlyView.as_view(), name='notifications-get-only'),
    path('profile/change-profile/', ProfileChangePostOnlyView.as_view(), name='profile-change-post-only'),
    path('profile/remove-profile/', ProfileRemovePostOnlyView.as_view(), name='profile-remove-post-only'),
    path('profile/update-bio/', BioUpdatePostOnlyView.as_view(), name='bio-update-post-only'),
]

register/urls.py
from django.urls import path
from .views import (
    choose_type_of_account, 
    SignUpTeacherInitialView, 
    SignUpStudentInitialView, 
    SignUpTeacherFinalView, 
    SignUpStudentFinalView,
    LogInView,
    ForgotPasswordView,
    ResetPasswordView,
    ChangePasswordView,
    LogoutView,
)

app_name = 'register'

urlpatterns = [
    path('create/', choose_type_of_account, name='create-account'),
    path('create/teacher/', SignUpTeacherInitialView.as_view(), name="create-teacher"),
    path('create/student/', SignUpStudentInitialView.as_view(), name="create-student"),
    path('teacher/activate-user/<uidb64>/<token>/', SignUpTeacherFinalView.as_view(), name='activate-teacher'),
    path('student/activate-user/<uidb64>/<token>/', SignUpStudentFinalView.as_view(), name='activate-student'),
    path('login/', LogInView.as_view(), name="log-in"),
    path('forgot-password/', ForgotPasswordView.as_view(), name="forgot-password"),
    path('reset-password/<uidb64>/<token>/', ResetPasswordView.as_view(template_name='register/reset_password.html'), name="reset-password"),
    path('change-password/', ChangePasswordView.as_view(), name="change-password"),
    path('logout/', LogoutView.as_view(), name="logout"),
]

templates/email_formats/account_activate.html
{% autoescape off %}

Hi {{ userObj.username }},

Email sent by {{ domain }} for verifying your account.

Please use the link below to verify your account.
http://{{ domain }}{% url 'activate-account' uidb64=uid token=token %}

Thanks for using our site!

The {{ domain }} team.

{% endautoescape %}

templates/email_formats/activate_student.html
{% autoescape off %}

Hi {{ userObj.username }},

Email sent by {{ domain }} for verifying your account.

Please use the link below to verify your account.
http://{{ domain }}{% url 'register:activate-student' uidb64=uid token=token %}

Thanks for using our site!

The {{ domain }} team.

{% endautoescape %}

templates/email_formats/activate_teacher.html
{% autoescape off %}

Hi {{ userObj.username }},

Email sent by {{ domain }} for verifying your account.

Please use the link below to verify your account.
http://{{ domain }}{% url 'register:activate-teacher' uidb64=uid token=token %}

Thanks for using our site!

The {{ domain }} team.

{% endautoescape %}

templates/email_formats/reset_password.html
{% autoescape off %}
<br>
Hi {{ user.username }}, <br><br>

Email sent by {{ site_name }} for resetting your password. <br><br>

Reset your password from here:
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'register:reset-password' uidb64=uid token=token %} <br><br>
{% endblock %}

Thanks for using our site! <br><br>

The {{ site_name }} team.

{% endautoescape %}